export const mockPets = [
  {
    id: 1,
    name: "Max",
    type: "dog",
    breed: "Golden Retriever",
    age: "3 years",
    gender: "Male",
    status: "lost",
    description:
      "Friendly golden retriever with a red collar. Last seen near Central Park. Responds to his name and loves treats.",
    area: "Downtown",
    date: "May 18, 2025",
    image: "/placeholder.svg?height=300&width=500",
    features: ["Red collar with name tag", "Slight limp in right hind leg", "Very friendly and approaches people"],
    contact: {
      name: "John Smith",
      phone: "(555) 123-4567",
      email: "john.smith@example.com",
    },
    location: {
      x: 25,
      y: 35,
    },
  },
  {
    id: 2,
    name: "Luna",
    type: "cat",
    breed: "Siamese",
    age: "2 years",
    gender: "Female",
    status: "found",
    description:
      "Siamese cat found wandering in the neighborhood. Very affectionate and well-groomed, likely someone's pet.",
    area: "Riverside",
    date: "May 19, 2025",
    image: "/placeholder.svg?height=300&width=500",
    features: ["Blue collar with bell", "Very vocal", "Distinctive blue eyes"],
    contact: {
      name: "Sarah Johnson",
      phone: "(555) 987-6543",
      email: "sarah.j@example.com",
    },
    location: {
      x: 65,
      y: 45,
    },
  },
  {
    id: 3,
    name: "Buddy",
    type: "dog",
    breed: "Labrador",
    age: "5 years",
    gender: "Male",
    status: "lost",
    description:
      "Black labrador with a green collar. Very friendly and responds to 'Buddy'. Missing since yesterday evening.",
    area: "Oakwood",
    date: "May 17, 2025",
    image: "/placeholder.svg?height=300&width=500",
    features: ["Green collar with ID tag", "Small white patch on chest", "Trained and responds to commands"],
    contact: {
      name: "Michael Brown",
      phone: "(555) 456-7890",
      email: "michael.b@example.com",
    },
    location: {
      x: 40,
      y: 60,
    },
  },
  {
    id: 4,
    name: "Oliver",
    type: "cat",
    breed: "Maine Coon",
    age: "4 years",
    gender: "Male",
    status: "lost",
    description: "Large Maine Coon cat with fluffy tail. Very distinctive appearance and friendly disposition.",
    area: "Hillside",
    date: "May 16, 2025",
    image: "/placeholder.svg?height=300&width=500",
    features: ["No collar but microchipped", "Very large with long fur", "Distinctive M marking on forehead"],
    contact: {
      name: "Emily Wilson",
      phone: "(555) 234-5678",
      email: "emily.w@example.com",
    },
    location: {
      x: 75,
      y: 25,
    },
  },
  {
    id: 5,
    name: "Unknown",
    type: "dog",
    breed: "Border Collie Mix",
    age: "Unknown",
    gender: "Female",
    status: "found",
    description: "Border Collie mix found near the community center. Very well-behaved and knows basic commands.",
    area: "Westside",
    date: "May 20, 2025",
    image: "/placeholder.svg?height=300&width=500",
    features: ["Black and white coloring", "No collar but well-groomed", "Knows commands like sit and stay"],
    contact: {
      name: "David Lee",
      phone: "(555) 345-6789",
      email: "david.l@example.com",
    },
    location: {
      x: 15,
      y: 70,
    },
  },
  {
    id: 6,
    name: "Charlie",
    type: "bird",
    breed: "Cockatiel",
    age: "1 year",
    gender: "Unknown",
    status: "lost",
    description:
      "Yellow and gray cockatiel that can whistle the first few notes of 'Happy Birthday'. Very friendly with people.",
    area: "Parkview",
    date: "May 15, 2025",
    image: "/placeholder.svg?height=300&width=500",
    features: ["Yellow crest and gray body", "Can whistle tunes", "Responds to name 'Charlie'"],
    contact: {
      name: "Lisa Garcia",
      phone: "(555) 567-8901",
      email: "lisa.g@example.com",
    },
    location: {
      x: 55,
      y: 15,
    },
  },
]
