import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "./providers/NextAuthProvider";
// import { ThemeProvider } from '@/context/ThemeProvider';
import { UserDataProvider } from "@/contexts/UserData";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserDataProvider>
        <NextAuthProvider>
          {/* <ThemeProvider> */}
        {children}
        {/* </ThemeProvider> */}
        </NextAuthProvider>
        </UserDataProvider>
        
      </body>
    </html>
  );
}
// import Navbar from "@/components/navbar"
// import Footer from "@/components/footer"
// import { Toaster } from "@/components/ui/toaster"
// import "./globals.css"

// export const metadata = {
//   title: "Animal's Club - Connect with Pet Services",
//   description: "A digital platform connecting pet owners with specialized centers and services.",
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <Navbar />
//         <main>{children}</main>
//         <Footer />
//         <Toaster />
//       </body>
//     </html>
//   )
// }

